test

diff --git a/.github/workflows/run-by-label.yaml b/.github/workflows/run-by-label.yaml
--- a/.github/workflows/run-by-label.yaml
+++ b/.github/workflows/run-by-label.yaml
@@ -15,13 +15,20 @@ env:
 
 jobs:
   integration-tests:
-    if: ${{ github.event.label.name == 'run:integration-tests' }}
     name: Integration Tests
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
         with:
           fetch-depth: 1
+
+      - name: check if label is correct
+        id: check_label
+        run: |
+          if [[ ! " ${GITHUB_EVENT_LABELS[*]} " =~ " run:integration-tests " ]]; then
+            echo "Label 'run:integration-tests' not found. Skipping integration tests."
+            exit 1
+          fi
 
       - run: echo "Running integration tests..."
         # Here you would add the actual commands to run your integration tests
